name = "DAQP"
uuid = "c47d62df-3981-49c8-9651-128b1cd08617"
authors = ["Daniel Arnström <daniel.arnstrom@liu.se>"]
version = "0.3.2"

[deps]
DAQP_jll = "5c51c916-43bf-57fe-9d62-13064ebbf40d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
DAQP_jll = "0.3.1"
MathOptInterface = "1.1"
julia = "1.6"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Random", "Test"]
